name: deepseek_api
description: A Flutter package for integrating with DeepSeek's API. Supports chat completions, model management, and streaming.
version: 0.0.8
homepage: https://github.com/habeebrahman021/deepseek_api
repository: https://github.com/habeebrahman021/deepseek_api
issue_tracker: https://github.com/habeebrahman021/deepseek_api/issues

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3

flutter:
